# Generated by Django 2.2.9 on 2020-01-21 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_editor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='editor',
            new_name='is_editor',
        ),
    ]
