# Generated by Django 2.2.9 on 2020-01-06 21:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Artist Name')),
                ('bio', models.TextField(blank=True, max_length=5000, verbose_name='Artist Bio')),
                ('role', models.CharField(choices=[('Artist', 'Artist'), ('Curator', 'Curator')], default='Artist', max_length=20)),
                ('public_url', models.CharField(blank=True, max_length=500, verbose_name='Artist Website')),
                ('public_twitter', models.CharField(blank=True, max_length=500, verbose_name='Artist Twitter')),
                ('public_instagram', models.CharField(blank=True, max_length=500, verbose_name='Artist Instagram')),
                ('private_email', models.CharField(blank=True, max_length=100, verbose_name='Contact Email (private)')),
                ('private_phone', models.CharField(blank=True, max_length=100, verbose_name='Contact Phone (private)')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modification_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
