# Generated by Django 2.2.12 on 2020-06-12 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='creation_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_creation_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artist',
            name='curator',
            field=models.BooleanField(default=False, verbose_name='Program Curator'),
        ),
        migrations.AddField(
            model_name='artist',
            name='modification_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_modification_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artist',
            name='role',
            field=models.CharField(choices=[('None', 'None'), ('Artist', 'Artist'), ('Commissioned', 'Commissioned Artist'), ('Storyteller', 'Storyteller')], default='Artist', max_length=20, verbose_name='Artist Type'),
        ),
    ]
